import { parseItemWithRarity, getItemById } from "./items";

const ASSET_BASE = "https://pub-87034a8f89f94b3d9149a9af7048ee14.r2.dev/";
const img = (f: string) => ASSET_BASE + "generated_images/" + f;

export const ITEM_IMAGES: Record<string, string> = {
  "Gold Coins": img("gold_coins_icon.png"),

  // Wood sources (skill actions)
  "Cactus Wood Source": img("cactus_wood_source_icon.webp"),
  "Darkwood": img("darkwood_source_icon.webp"),
  "Dragon Wood": img("dragon_wood_source_icon.webp"),
  "Elderwood": img("elderwood_source_icon.webp"),
  "Ice Wood": img("ice_wood_source_icon.webp"),
  "Petrified Wood": img("petrified_wood_source_icon.webp"),
  "Normal Tree": img("normal_tree_icon.webp"),
  "woodcutting_normal_tree": img("normal_tree_icon.webp"),
  "Oak Tree": img("oak_tree_icon.webp"),
  "woodcutting_oak_tree": img("oak_tree_icon.webp"),
  "Willow Tree": img("willow_tree_icon.webp"),
  "woodcutting_willow_tree": img("willow_tree_icon.webp"),
  "Maple Tree": img("maple_tree_icon.webp"),
  "woodcutting_maple_tree": img("maple_tree_icon.webp"),
  "Yew Tree": img("yew_tree_icon.webp"),
  "woodcutting_yew_tree": img("yew_tree_icon.webp"),
  "Magic Tree": img("magic_tree_icon.webp"),
  "woodcutting_magic_tree": img("magic_tree_icon.webp"),
  "Elderwood Log": img("elderwood_source_icon.webp"),
  "woodcutting_elderwood": img("elderwood_source_icon.webp"),
  "Petrified Wood Log": img("petrified_wood_source_icon.webp"),
  "woodcutting_petrified_wood": img("petrified_wood_source_icon.webp"),
  "Cactus Wood": img("cactus_wood_source_icon.webp"),
  "woodcutting_cactus_wood": img("cactus_wood_source_icon.webp"),
  "Darkwood Log": img("darkwood_source_icon.webp"),
  "woodcutting_darkwood": img("darkwood_source_icon.webp"),
  "Dragon Wood Log": img("dragon_wood_source_icon.webp"),
  "woodcutting_dragon_wood": img("dragon_wood_source_icon.webp"),
  "Ice Wood Log": img("ice_wood_source_icon.webp"),
  "woodcutting_ice_wood": img("ice_wood_source_icon.webp"),
  "Void Root": img("void_root_source_icon.webp"),
  "woodcutting_void_root": img("void_root_source_icon.webp"),

  // Logs (inventory items)
  "normal_logs": img("normal_logs_icon.png"),
  "oak_logs": img("oak_logs_icon.png"),
  "willow_logs": img("willow_logs_icon.png"),
  "maple_logs": img("maple_logs_icon.png"),
  "yew_logs": img("yew_logs_icon.png"),
  "magic_logs": img("magic_logs_icon.webp"),
  "elderwood_logs": img("elderwood_logs_icon.webp"),
  "petrified_logs": img("petrified_logs_icon.webp"),
  "cactus_logs": img("cactus_logs_icon.webp"),
  "darkwood_logs": img("darkwood_logs_icon.webp"),
  "dragon_logs": img("dragon_logs_icon.webp"),
  "ice_logs": img("ice_logs_icon.webp"),
  "void_logs": img("void_logs_icon.webp"),

  // Ash materials
  "basic_ash": img("basic_ash_icon.png"),
  "oak_ash": img("oak_ash_icon.png"),
  "willow_ash": img("willow_ash_icon.png"),
  "maple_ash": img("maple_ash_icon.png"),
  "yew_ash": img("yew_ash_icon.png"),
  "magic_ash": img("magic_ash_icon.png"),
  "elder_ash": img("elder_ash_icon.png"),
  "petrified_ash": img("petrified_ash_icon.png"),
  "cactus_ash": img("cactus_ash_icon.png"),
  "darkwood_ash": img("darkwood_ash_icon.png"),
  "dragon_ash": img("dragon_ash_icon.png"),
  "ice_ash": img("ice_ash_icon.png"),
  "void_ash": img("void_ash_icon.png"),

  // Ores
  "Copper Ore": img("copper_ore_pixel_art_icon.webp"),
  "Tin Ore": img("tin_ore_pixel_art_icon.webp"),
  "Iron Ore": img("iron_ore_pixel_art_icon.webp"),
  "Silver Ore": img("silver_ore_pixel_art_icon.webp"),
  "Coal": img("coal_pixel_art_icon.webp"),
  "Gold Ore": img("gold_ore_pixel_art_icon.webp"),
  "Mithril Ore": img("mithril_ore_chunk_icon.webp"),
  "Adamant Ore": img("adamant_ore_chunk_icon.webp"),
  "Rune Ore": img("rune_ore_chunk_icon.webp"),
  "Dragonstone": img("material_dragonstone.webp"),
  "Moonstone": img("material_moonstone.webp"),
  "Obsidian Shard": img("material_obsidian_shard.webp"),
  "Shadow Ore": img("material_shadow_ore.webp"),
  "Sun Crystal": img("material_sun_crystal.webp"),
  "Froststone": img("material_froststone.webp"),
  "Void Crystal": img("material_void_crystal.webp"),
  "ore_essence": img("ore_essence_pixel_art_icon.png"),

  // Bars
  "Bronze Bar": img("bronze_bar_pixel_art.webp"),
  "Iron Bar": img("iron_bar_pixel_art.webp"),
  "Steel Bar": img("steel_bar_pixel_art.webp"),
  "Silver Bar": img("silver_bar_pixel_art.webp"),
  "Gold Bar": img("gold_bar_pixel_art.webp"),
  "Mithril Bar": img("mithril_bar_pixel_art.webp"),
  "Adamant Bar": img("adamant_bar_pixel_art.webp"),
  "Rune Bar": img("rune_bar_pixel_art.webp"),
  "Void Bar": img("material_void_bar.webp"),

  // Hunting animals (skill actions)
  "Rabbit": img("rabbit_icon.webp"),
  "hunting_rabbit": img("rabbit_icon.webp"),
  "Sheep": img("sheep_icon.webp"),
  "hunting_sheep": img("sheep_icon.webp"),
  "Deer": img("deer_icon.webp"),
  "hunting_deer": img("deer_icon.webp"),
  "Wild Boar": img("boar_icon.webp"),
  "hunting_boar": img("boar_icon.webp"),
  "Mountain Goat": img("mountain_goat_icon.webp"),
  "hunting_mountain_goat": img("mountain_goat_icon.webp"),
  "Desert Fox": img("desert_fox_icon.webp"),
  "hunting_desert_fox": img("desert_fox_icon.webp"),
  "Wild Camel": img("camel_icon.webp"),
  "hunting_camel": img("camel_icon.webp"),
  "Shadow Wolf": img("shadow_wolf_icon.webp"),
  "hunting_shadow_wolf": img("shadow_wolf_icon.webp"),
  "Dark Panther": img("dark_panther_icon.webp"),
  "hunting_dark_panther": img("dark_panther_icon.webp"),
  "Ice Bear": img("ice_bear_icon.webp"),
  "hunting_ice_bear": img("ice_bear_icon.webp"),
  "Frost Tiger": img("frost_tiger_icon.webp"),
  "hunting_frost_tiger": img("frost_tiger_icon.webp"),
  "Wyvern": img("wyvern_icon.webp"),
  "hunting_wyvern": img("wyvern_icon.webp"),
  "Celestial Stag": img("celestial_stag_icon.webp"),
  "hunting_celestial_stag": img("celestial_stag_icon.webp"),
  "Void Beast": img("void_beast_icon.webp"),
  "hunting_void_beast": img("void_beast_icon.webp"),
  "Abyssal Creature": img("abyssal_creature_icon.webp"),
  "hunting_abyssal_creature": img("abyssal_creature_icon.webp"),

  // Pelts and hides (inventory items)
  "rabbit_pelt": img("rabbit_pelt_icon.webp"),
  "wool": img("wool_icon.webp"),
  "deer_hide": img("deer_hide_icon.webp"),
  "boar_hide": img("boar_hide_icon.webp"),
  "goat_pelt": img("goat_pelt_icon.webp"),
  "fox_pelt": img("fox_pelt_icon.webp"),
  "camel_hide": img("camel_hide_icon.webp"),
  "shadow_wolf_pelt": img("shadow_wolf_pelt_icon.webp"),
  "panther_pelt": img("panther_pelt_icon.webp"),
  "ice_bear_pelt": img("ice_bear_pelt_icon.webp"),
  "frost_tiger_pelt": img("frost_tiger_pelt_icon.webp"),
  "wyvern_leather": img("wyvern_leather_icon.webp"),
  "celestial_hide": img("celestial_hide_icon.webp"),
  "void_beast_hide": img("void_beast_hide_icon.webp"),

  // Hunting crafting materials
  "Raw Hide": img("material_raw_hide.png"),
  "raw_hide": img("material_raw_hide.png"),
  "Leather Strip": img("material_leather_strip.png"),
  "leather_strip": img("material_leather_strip.png"),
  "Linen Cloth": img("material_linen_cloth.png"),
  "linen_cloth": img("material_linen_cloth.png"),
  "Hardened Leather": img("material_hardened_leather.png"),
  "hardened_leather": img("material_hardened_leather.png"),
  "Silk Thread": img("material_silk_thread.png"),
  "silk_thread": img("material_silk_thread.png"),
  "Studded Leather": img("material_studded_leather.png"),
  "studded_leather": img("material_studded_leather.png"),
  "Mystic Cloth": img("material_mystic_cloth.png"),
  "mystic_cloth": img("material_mystic_cloth.png"),
  "Ranger Leather": img("material_ranger_leather.png"),
  "ranger_leather": img("material_ranger_leather.png"),
  "Arcane Silk": img("material_arcane_silk.png"),
  "arcane_silk": img("material_arcane_silk.png"),
  "Shadow Leather": img("material_shadow_leather.png"),
  "shadow_leather": img("material_shadow_leather.png"),
  "Divine Cloth": img("material_divine_cloth.png"),
  "divine_cloth": img("material_divine_cloth.png"),
  "Dragon Leather": img("material_dragon_leather.png"),
  "dragon_leather": img("material_dragon_leather.png"),
  "Void Silk": img("material_void_silk.png"),
  "void_silk": img("material_void_silk.png"),
  "Void Leather": img("material_void_leather.png"),
  "void_leather": img("material_void_leather.png"),

  // Raw fish
  "Raw Shrimp": img("raw_shrimp_pixel_art_icon.webp"),
  "Raw Sardine": img("sardine_fish_pixel_art_icon.webp"),
  "Raw Herring": img("herring_fish_pixel_art_icon.webp"),
  "Raw Trout": img("trout_fish_pixel_art_icon.webp"),
  "Raw Salmon": img("salmon_fish_pixel_art_icon.webp"),
  "Raw Tuna": img("raw_tuna_fish_icon.webp"),
  "Raw Lobster": img("raw_lobster_icon.webp"),
  "Raw Swordfish": img("raw_swordfish_icon.webp"),
  "Raw Shark": img("raw_shark_icon.webp"),
  "Raw Manta Ray": img("raw_manta_ray_pixel_art.webp"),
  "Raw Sea Turtle": img("raw_sea_turtle_pixel_art.webp"),
  "Raw Cave Fish": img("material_cave_fish.webp"),
  "Raw Dragon Fish": img("material_dragon_fish.webp"),
  "Raw Frost Fish": img("material_frost_fish.webp"),
  "Raw Lava Fish": img("material_lava_fish.webp"),
  "Raw Sand Eel": img("material_sand_eel.webp"),
  "Raw Spirit Fish": img("material_spirit_fish.webp"),
  "Raw Void Fish": img("material_void_fish.webp"),
  "Spirit Fish": img("material_spirit_fish.webp"),
  "Void Fish": img("material_void_fish.webp"),
  "Cave Fish": img("material_cave_fish.webp"),
  "Dragon Fish": img("material_dragon_fish.webp"),
  "Frost Fish": img("material_frost_fish.webp"),
  "Lava Fish": img("material_lava_fish.webp"),
  "Sand Eel": img("material_sand_eel.webp"),

  // Cooked food
  "Cooked Rabbit": img("cooked_rabbit_pixel_art.webp"),
  "Cooked Meat": img("cooked_meat_pixel_art.webp"),
  "Cooked Shrimp": img("cooked_shrimp_pixel_art.webp"),
  "Cooked Sardine": img("cooked_sardine_pixel_art.webp"),
  "Cooked Herring": img("cooked_herring_pixel_art.webp"),
  "Cooked Trout": img("cooked_trout_pixel_art.webp"),
  "Cooked Salmon": img("cooked_salmon_pixel_art.webp"),
  "Cooked Tuna": img("cooked_tuna_pixel_art.webp"),
  "Cooked Lobster": img("cooked_lobster_pixel_art.webp"),
  "Cooked Swordfish": img("cooked_swordfish_pixel_art.webp"),
  "Cooked Shark": img("cooked_shark_pixel_art.webp"),
  "Cooked Manta Ray": img("cooked_manta_ray_pixel_art.webp"),
  "Cooked Sea Turtle": img("cooked_sea_turtle_pixel_art.webp"),
  "Cooked Cave Fish": img("food_cave_fish.webp"),
  "Cooked Dragon Fish": img("food_dragon_fish.webp"),
  "Cooked Frost Fish": img("food_frost_fish.webp"),
  "Cooked Lava Fish": img("food_lava_fish.webp"),
  "Cooked Sand Eel": img("food_sand_eel.webp"),
  "Cooked Spirit Fish": img("food_spirit_fish.webp"),
  "Cooked Void Fish": img("food_void_fish.webp"),
  "Chicken": img("cooked_chicken_pixel_art.webp"),
  "Goblin Kebab": img("goblin_kebab_pixel_art.webp"),
  "Spider Soup": img("spider_soup_pixel_art.webp"),
  "Dragon Steak": img("dragon_steak_food_item.webp"),
  "Meat Pie": img("meat_pie_pixel_art.webp"),
  "Fish Stew": img("fish_stew_pixel_art.webp"),
  "Orc Roast": img("orc_roast_pixel_art.webp"),
  "Wyvern Steak": img("food_wyvern_steak.webp"),
  "Drake Roast": img("food_drake_roast.webp"),
  "Void Stew": img("food_void_stew.webp"),
  "Spirit Feast": img("food_spirit_feast.webp"),
  "Frost Dragon Stew": img("food_frost_dragon_stew.webp"),

  // Raw materials (combat drops)
  "Goblin Ear": img("goblin_ear_pixel_art.webp"),
  "Spider Silk": img("spider_silk_pixel_art.webp"),
  "Venom Sac": img("venom_sac_pixel_art.webp"),
  "Rotten Flesh": img("rotten_flesh_pixel_art.webp"),
  "Orc Tusk": img("orc_tusk_pixel_art.webp"),
  "Dark Essence": img("dark_essence_pixel_art.webp"),
  "Dragon Scale": img("dragon_scale_pixel_art.webp"),
  "Dragon Bone": img("dragon_bone_pixel_art.webp"),
  "Feather": img("feather_pixel_art.webp"),
  "Raw Rabbit": img("raw_rabbit_pixel_art.webp"),
  "Soft Fur": img("soft_fur_pixel_art.webp"),
  "Wolf Pelt": img("wolf_pelt_pixel_art.webp"),
  "Wolf Fang": img("wolf_fang_pixel_art.webp"),
  "Raw Meat": img("raw_meat_pixel_art.webp"),
  "Bandit Mask": img("bandit_mask_pixel_art.webp"),
  "Bat Wing": img("bat_wing_pixel_art.webp"),
  "Scorpion Stinger": img("scorpion_stinger_pixel_art.webp"),
  "Sand Essence": img("sand_essence_pixel_art.webp"),
  "Ancient Bandage": img("ancient_bandage_pixel_art.webp"),
  "Djinn Essence": img("djinn_essence_pixel_art.webp"),
  "Shadow Cloak": img("shadow_cloak_pixel_art.webp"),
  "Wyvern Scale": img("wyvern_scale_pixel_art.webp"),
  "Raw Wyvern Meat": img("raw_wyvern_meat_pixel_art.webp"),
  "Drake Scale": img("drake_scale_pixel_art.webp"),
  "Fire Essence": img("fire_essence_pixel_art.webp"),
  "Raw Chicken": img("raw_chicken_pixel_art.webp"),
  "Bear Pelt": img("bear_pelt_pixel_art.webp"),
  "Giant Rat Tail": img("giant_rat_tail_pixel_art.webp"),
  "Bone": img("bone_pixel_art.webp"),
  "Bones": img("bone_pixel_art.webp"),

  // Rare materials
  "phoenix_feather": img("feather_pixel_art.webp"),
  "frost_dragon_scale": img("material_frost_dragon_scale_v2.webp"),
  "void_crystal_shard": img("void_crystal_shard_icon.png"),
  "ancient_dragon_core": img("material_ancient_dragon_core.png"),
  "shadow_essence_gem": img("shadow_essence_gem_icon.png"),
  "thunder_drake_horn": img("orc_tusk_pixel_art.webp"),
  "ice_phoenix_plume": img("material_ice_phoenix_plume.png"),
  "frozen_crystal": img("material_frozen_crystal_v2.webp"),
  "wyrm_scale": img("wyrm_scale_v2.webp"),
  "ancient_froststone": img("material_ancient_froststone_v2.webp"),
  "frozen_essence": img("frozen_essence_ice_bottle.webp"),
  "frost_heart": img("frost_heart_ice_crystal.webp"),
  "frozen_pelt": img("bear_pelt_pixel_art.webp"),
  "Wyvern Wing Fragment": img("wyvern_wing_fragment_icon.webp"),
  "Drake Fire Essence": img("drake_fire_essence_icon.webp"),
  "Elder Dragon Heart": img("elder_dragon_heart_icon.webp"),
  "Ancient Dragon Spirit": img("ancient_dragon_spirit_icon.webp"),
  "hydra_scale": img("material_hydra_scale.png"),
  "verdant_heartwood": img("material_verdant_heartwood.png"),
  "celestial_fabric": img("material_celestial_fabric.png"),
  "oracle_fabric": img("material_oracle_fabric.png"),
  "golem_core": img("golem_core_material_icon.png"),
  "giant_ice_shard": img("material_giant_ice_shard.png"),
  "shadow_core": img("shadow_core_void_sphere.png"),
  "void_essence": img("void_essence_cosmic_bottle.png"),
  "void_fragment": img("void_fragment_dark_shard.png"),
  "dark_lord_fragment": img("dark_lord_crown_icon.png"),
  "pure_void_crystal": img("material_void_crystal.webp"),
  "void_core": img("void_essence_crystal_icon.png"),
  "void_knight_fragment": img("void_fragment_dark_shard.png"),

  // Weapons
  "Bronze Sword": img("bronze_sword_pixel_art.webp"),
  "Bronze Dagger": img("bronze_dagger_new.png"),
  "Iron Sword": img("iron_sword_pixel_art.webp"),
  "Iron Dagger": img("iron_dagger_pixel_art.webp"),
  "Iron Longsword": img("iron_longsword_pixel_art.webp"),
  "Steel Sword": img("steel_sword_pixel_art.webp"),
  "Steel Scimitar": img("steel_scimitar_pixel_art.webp"),
  "Goblin Blade": img("goblin_blade_new.png"),
  "goblin_blade": img("goblin_blade_new.png"),
  "Venomous Dagger": img("venomous_dagger_pixel_art.webp"),
  "Spider Fang Sword": img("spider_fang_sword_pixel_art.webp"),
  "Mithril Sword": img("mithril_sword_pixel_art.webp"),
  "Mithril Battleaxe": img("mithril_battleaxe_pixel_art.webp"),
  "Orcish Cleaver": img("orcish_cleaver_pixel_art.webp"),
  "Tusk Blade": img("tusk_blade_pixel_art.webp"),
  "Adamant Sword": img("adamant_sword_pixel_art.webp"),
  "Bronze Warhammer": img("bronze_hammer_weapon_icon.webp"),
  "Iron Warhammer": img("iron_hammer_weapon_icon.webp"),
  "Steel Warhammer": img("steel_hammer_weapon_icon.webp"),
  "Mithril Warhammer": img("mithril_hammer_weapon_icon.webp"),
  "Adamant Warhammer": img("adamant_hammer_weapon_icon.webp"),
  "Rune Warhammer": img("rune_hammer_weapon_icon.webp"),
  "Dragon Warhammer": img("dragon_hammer_weapon_icon.webp"),
  "Shadow Blade": img("shadow_blade_pixel_art.webp"),
  "Nightmare Sword": img("nightmare_sword_pixel_art.webp"),
  "Rune Sword": img("rune_sword_pixel_art.webp"),
  "Dragon Sword": img("dragon_sword_pixel_art.webp"),
  "Dragonbone Blade": img("dragonbone_blade_pixel_art.webp"),
  "Silver Dagger": img("silver_dagger_pixel_art.webp"),
  "Shadow Dagger": img("shadow_dagger_weapon_icon.png"),
  "Drake Fire Sword": img("drake_fire_sword_weapon.png"),
  "Scorpion Stinger Spear": img("scorpion_stinger_spear_new.png"),
  "shortbow": img("shortbow_weapon_icon.png"),
  "darkwood_bow": img("darkwood_bow_weapon_icon.png"),
  "crypt_shortbow": img("crypt_shortbow_icon.png"),
  "boneclaw_dagger": img("boneclaw_dagger_icon.png"),
  "soulfire_bow": img("soulfire_bow_icon.png"),
  "phantom_dagger": img("phantom_dagger_icon.png"),
  "dragonbone_longbow": img("dragonbone_longbow_icon.png"),
  "flamescale_staff": img("flamescale_staff_icon.png"),
  "voidstrike_bow": img("voidstrike_bow_icon.png"),
  "abyssal_dagger": img("abyssal_dagger_icon.png"),
  "abyssal_staff": img("abyssal_staff_icon.png"),
  "phoenix_staff": img("equip_phoenix_staff.png"),
  "infernal_staff": img("equip_infernal_staff.png"),
  "shadow_dagger": img("equip_shadow_dagger.png"),
  "frost_blade": img("equip_frost_blade.webp"),
  "frost_bow": img("equip_frost_bow.png"),
  "obsidian_blade": img("equip_obsidian_blade.webp"),
  "verdant_sword": img("equip_verdant_sword.webp"),
  "sun_blade": img("equip_sun_blade.webp"),
  "void_sword": img("equip_void_sword.webp"),
  "Void Blade": img("equip_void_blade.webp"),
  "Void Dagger": img("equip_void_dagger.webp"),
  "Void Battleaxe": img("equip_void_battleaxe.webp"),
  "void_warhammer": img("equip_void_warhammer.png"),
  "thunder_hammer": img("dragon_hammer_weapon_icon.webp"),
  "triple_loot_staff": img("equip_witch_ice_staff.png"),
  "Frostfire Blade": img("equip_frostfire_blade.png"),
  "Dark Knight Sword": img("dark_knight_sword_icon.webp"),
  "Shadow Hunter Dagger": img("shadow_hunter_dagger_icon.webp"),
  "Orc Warlord Axe": img("orc_warlord_axe_icon.webp"),
  "Dark Knight Sword Piece": img("dark_knight_sword_piece.webp"),
  "Shadow Dagger Piece": img("shadow_dagger_piece_icon.webp"),
  "Orc Axe Piece": img("orc_axe_piece_icon.webp"),
  "abyssal_trident": img("equip_abyssal_trident.png"),
  "hydra_fang_dagger": img("equip_hydra_fang_dagger.png"),
  "vine_lash_whip": img("equip_vine_lash_whip.png"),
  "drake_staff": img("drake_staff_icon.png"),
  "spider_queen_staff": img("spider_queen_staff_icon.png"),
  "shadow_lord_staff": img("shadow_lord_staff_icon.png"),
  "mummy_lord_staff": img("mummy_lord_staff_icon.png"),
  "orc_shaman_staff": img("orc_shaman_staff_icon.png"),
  "troll_hammer_piece": img("troll_hammer_piece_fragment.png"),
  "giant's_hammer_shard": img("giants_hammer_shard_icon.png"),
  "giants_hammer_shard": img("giants_hammer_shard_icon.png"),
  "dragon_hammer_head": img("dragon_hammer_head_icon.png"),
  "demon_shard": img("titan_fragment_demon_shard.png"),

  // Shields
  "Bronze Shield": img("bronze_shield_pixel_art.webp"),
  "Bronze Buckler": img("bronze_buckler_pixel_art.webp"),
  "Iron Shield": img("iron_shield_pixel_art.webp"),
  "Iron Kite Shield": img("iron_kite_shield_new.png"),
  "Steel Shield": img("steel_shield_pixel_art.webp"),
  "Steel Tower Shield": img("steel_tower_shield_pixel_art.webp"),
  "Steel Buckler": img("steel_buckler_pixel_art_icon.webp"),
  "Goblin Barrier": img("goblin_barrier_pixel_art.webp"),
  "Silken Guard": img("silken_guard_pixel_art.webp"),
  "Venom Ward": img("massive_venom_ward_shield.png"),
  "Mithril Shield": img("mithril_shield_pixel_art.webp"),
  "Mithril Defender": img("mithril_defender_pixel_art.webp"),
  "Orcish Bulwark": img("orcish_bulwark_pixel_art.webp"),
  "Tusked Shield": img("tusked_shield_pixel_art.webp"),
  "Adamant Shield": img("adamant_shield_pixel_art.webp"),
  "Adamant Buckler": img("adamant_buckler_pixel_art_icon.webp"),
  "Adamant Fortress": img("adamant_fortress_pixel_art.webp"),
  "Shadow Barrier": img("shadow_barrier_pixel_art.webp"),
  "Nightmare Guard": img("nightmare_guard_pixel_art.webp"),
  "Rune Shield": img("rune_shield_pixel_art.webp"),
  "Dragon Shield": img("dragon_shield_pixel_art.webp"),
  "Dragonbone Bulwark": img("dragonbone_bulwark_pixel_art.webp"),
  "Void Shield": img("equip_void_shield.webp"),
  "Void Aegis": img("equip_void_aegis.png"),
  "dragon_scale_shield": img("equip_dragon_scale_shield.png"),
  "crypt_ward_shield": img("crypt_ward_shield_icon.png"),

  // Helmets
  "Bronze Helmet": img("bronze_helmet_pixel_art.webp"),
  "Iron Helmet": img("iron_helmet_pixel_art.webp"),
  "Steel Helmet": img("steel_helmet_new.png"),
  "Mithril Helmet": img("mithril_helmet_pixel_art.webp"),
  "Orcish Mithril Helmet": img("orcish_mithril_helmet_icon.webp"),
  "Dark Mithril Helmet": img("dark_mithril_helmet_icon.webp"),
  "Wyvern Mithril Helmet": img("wyvern_mithril_helmet_icon.webp"),
  "Adamant Helmet": img("adamant_helmet_pixel_art.webp"),
  "Rune Helmet": img("rune_helmet_pixel_art.webp"),
  "Dragon Helmet": img("dragon_helmet_pixel_art.webp"),
  "Shadow Helm": img("shadow_helm_pixel_art.webp"),
  "Crown of Flames": img("crown_of_flames_pixel_art.webp"),
  "Silver Tiara": img("silver_tiara_pixel_art.webp"),
  "Fur Hunter Mask": img("fur_hunter_mask_new.png"),
  "Spider Silk Hood": img("spider_silk_hood_new.png"),
  "Void Helmet": img("equip_void_helmet.png"),
  "void_helm": img("equip_void_helm.webp"),
  "Void King Crown": img("equip_void_king_crown.webp"),
  "Dark Lord Crown": img("dark_lord_crown_icon.webp"),
  "phoenix_helm": img("equip_phoenix_helm.png"),
  "dunes_helm": img("equip_dunes_helm.webp"),
  "frost_helm": img("equip_frost_helm.webp"),
  "obsidian_helm": img("equip_obsidian_helm.webp"),
  "quarry_helm": img("equip_quarry_helm.webp"),
  "verdant_helm": img("equip_verdant_helm.webp"),
  "Desert Helmet": img("equip_desert_helmet.png"),
  "natures_crown": img("equip_natures_crown.png"),

  // Platebodies
  "Bronze Platebody": img("bronze_platebody_pixel_art.webp"),
  "Iron Platebody": img("iron_platebody_pixel_art.webp"),
  "Steel Platebody": img("steel_platebody_pixel_art.webp"),
  "Mithril Platebody": img("mithril_platebody_pixel_art.webp"),
  "Orcish Mithril Platebody": img("orcish_mithril_platebody_icon.webp"),
  "Dark Mithril Platebody": img("dark_mithril_platebody_icon.webp"),
  "Wyvern Mithril Platebody": img("wyvern_mithril_platebody_icon.webp"),
  "Adamant Platebody": img("adamant_platebody_pixel_art.webp"),
  "Rune Platebody": img("rune_platebody_pixel_art.webp"),
  "Dragon Platebody": img("dragon_platebody_pixel_art.webp"),
  "Shadow Platebody": img("shadow_platebody_pixel_art.webp"),
  "Mithril Armor": img("mithril_armor_pixel_art.webp"),
  "Desert Guardian Armor": img("desert_guardian_armor_icon.png"),
  "Wyvern Scale Armor": img("wyvern_scale_armor_icon.png"),
  "Infernal Armor": img("infernal_armor_icon.png"),
  "Void Platebody": img("equip_void_platebody.webp"),
  "void_set_platebody": img("equip_void_platebody.webp"),
  "dunes_platebody": img("equip_dunes_platebody.webp"),
  "frost_platebody": img("equip_frost_platebody.webp"),
  "obsidian_platebody": img("equip_obsidian_platebody.webp"),
  "quarry_platebody": img("equip_quarry_platebody.webp"),
  "verdant_platebody": img("equip_verdant_platebody.webp"),
  "Desert Platebody": img("equip_desert_platebody.png"),
  "Earthstone Platebody": img("equip_earthstone_platebody.png"),
  "dragonscale_armor": img("dragonscale_armor_icon.png"),

  // Platelegs
  "Bronze Platelegs": img("bronze_platelegs_pixel_art_icon.png"),
  "Iron Platelegs": img("iron_platelegs_pixel_art_icon.png"),
  "Steel Platelegs": img("steel_platelegs_pixel_art_icon.png"),
  "Mithril Platelegs": img("mithril_platelegs_pixel_art_icon.png"),
  "Orcish Mithril Platelegs": img("orcish_mithril_platelegs_icon.webp"),
  "Dark Mithril Platelegs": img("dark_mithril_platelegs_icon.webp"),
  "Wyvern Mithril Platelegs": img("wyvern_mithril_platelegs_icon.webp"),
  "Adamant Platelegs": img("adamant_platelegs_pixel_art_icon.png"),
  "Rune Platelegs": img("rune_platelegs_pixel_art_icon.png"),
  "Dragon Platelegs": img("dragon_platelegs_pixel_art_icon.png"),
  "Shadow Platelegs": img("shadow_platelegs_pixel_art_icon.png"),
  "Void Platelegs": img("equip_void_platelegs.webp"),
  "void_platelegs": img("equip_void_platelegs.webp"),
  "dunes_platelegs": img("equip_dunes_platelegs.webp"),
  "frost_platelegs": img("equip_frost_platelegs.webp"),
  "obsidian_platelegs": img("equip_obsidian_platelegs.webp"),
  "quarry_platelegs": img("equip_quarry_platelegs.webp"),
  "verdant_platelegs": img("equip_verdant_platelegs.webp"),
  "Desert Platelegs": img("equip_desert_platelegs.png"),

  // Gloves
  "Bronze Gloves": img("bronze_gloves_new.png"),
  "Iron Gloves": img("iron_gloves_pixel_art.webp"),
  "Steel Gloves": img("steel_gloves_pixel_art.webp"),
  "Mithril Gloves": img("mithril_gloves_pixel_art.webp"),
  "Orcish Mithril Gloves": img("orcish_mithril_gloves_icon.webp"),
  "Dark Mithril Gloves": img("dark_mithril_gloves_icon.webp"),
  "Wyvern Mithril Gloves": img("wyvern_mithril_gloves_icon.webp"),
  "Adamant Gloves": img("adamant_gloves_pixel_art.webp"),
  "Rune Gloves": img("rune_gloves_pixel_art.webp"),
  "Dragon Gloves": img("dragon_gloves_pixel_art.webp"),
  "Void Gloves": img("equip_void_gloves.png"),
  "Desert Gloves": img("equip_desert_gloves.png"),
  "dragonclaw_gauntlets": img("dragonclaw_gauntlets_icon.png"),

  // Boots
  "Bronze Boots": img("bronze_boots_pixel_art.webp"),
  "Iron Boots": img("iron_boots_pixel_art.webp"),
  "Steel Boots": img("steel_boots_pixel_art.webp"),
  "Mithril Boots": img("mithril_boots_pixel_art.webp"),
  "Orcish Mithril Boots": img("orcish_mithril_boots_icon.webp"),
  "Dark Mithril Boots": img("dark_mithril_boots_icon.webp"),
  "Wyvern Mithril Boots": img("wyvern_mithril_boots_icon.webp"),
  "Adamant Boots": img("adamant_boots_pixel_art.webp"),
  "Rune Boots": img("rune_boots_pixel_art.webp"),
  "Dragon Boots": img("dragon_boots_pixel_art.webp"),
  "Void Boots": img("equip_void_boots.webp"),
  "void_boots": img("equip_void_boots.webp"),
  "dunes_boots": img("equip_dunes_boots.webp"),
  "frost_boots": img("equip_frost_boots.webp"),
  "obsidian_boots": img("equip_obsidian_boots.webp"),
  "quarry_boots": img("equip_quarry_boots.webp"),
  "verdant_boots": img("equip_verdant_boots.webp"),
  "Desert Boots": img("equip_desert_boots.png"),
  "dustwalker_boots": img("dustwalker_boots_icon.png"),
  "wraith_boots": img("wraith_boots_icon.png"),
  "voidwalker_boots": img("voidwalker_boots_icon.png"),

  // Jewelry
  "Silver Ring": img("silver_ring_pixel_art.webp"),
  "Silver Amulet": img("silver_amulet_pixel_art.webp"),
  "Gold Ring": img("gold_ring_pixel_art.webp"),
  "Gold Amulet": img("gold_amulet_pixel_art.webp"),
  "Quarry Amulet": img("quarry_amulet_pixel_art.webp"),
  "Starlit Amulet": img("starlit_amulet_pixel_art.webp"),
  "Nightfall Amulet": img("nightfall_amulet_pixel_art.webp"),
  "Dragon Amulet": img("dragon_amulet_pixel_art.webp"),
  "Bronze Ring": img("bronze_ring_pixel_art_icon.png"),
  "Bronze Amulet": img("bronze_amulet_pixel_art_icon.png"),
  "Iron Ring": img("iron_ring_pixel_art_icon.png"),
  "Iron Amulet": img("iron_amulet_pixel_art_icon.png"),
  "Steel Ring": img("steel_ring_pixel_art_icon.png"),
  "Steel Amulet": img("steel_amulet_pixel_art_icon.png"),
  "Mithril Ring": img("mithril_ring_pixel_art_icon.png"),
  "Mithril Amulet": img("mithril_amulet_new.png"),
  "Adamant Ring": img("adamant_ring_pixel_art_icon.png"),
  "Adamant Amulet": img("adamant_amulet_pixel_art_icon.png"),
  "Rune Ring": img("rune_ring_pixel_art_icon.png"),
  "Rune Amulet": img("rune_amulet_pixel_art_icon.png"),
  "Dragon Essence Ring": img("dragon_essence_ring_icon.png"),
  "Spider Queen Ring": img("spider_queen_ring_icon.webp"),
  "Void Ring": img("equip_void_ring.png"),
  "Void Lord Ring": img("equip_void_lord_ring.webp"),
  "Void Amulet": img("equip_void_amulet.png"),
  "void_heart_amulet": img("void_heart_amulet_icon.png"),
  "Nature Warden Ring": img("equip_nature_warden_ring.webp"),
  "quarry_pickaxe": img("equip_quarry_pickaxe.webp"),

  // Capes
  "Desert Cape": img("desert_cape_pixel_art.webp"),
  "Obsidian Cape": img("obsidian_cape_pixel_art.webp"),
  "Dragonfire Cape": img("dragonfire_cape_pixel_art.webp"),
  "Infernal Cape": img("infernal_cape_pixel_art.webp"),
  "Bat Wing Cloak": img("bat_wing_cloak_new.png"),
  "Wolf Cloak": img("wolf_cloak_pixel_art_icon.png"),
  "Shadow Cape": img("shadow_cape_new.png"),
  "Wyvern Cape": img("wyvern_cape_new.png"),
  "Dragonscale Cape": img("dragonscale_cape_pixel_icon.png"),
  "Dragon Cloak": img("dragon_cloak_equipment_icon.webp"),

  // Cloth armor T1-T8
  "Linen Hat": img("linen_hat_t1.png"),
  "linen_hat_t1": img("linen_hat_t1.png"),
  "Linen Robe": img("linen_robe_t1.png"),
  "linen_robe_t1": img("linen_robe_t1.png"),
  "Linen Sandals": img("linen_sandals_t1.png"),
  "linen_sandals_t1": img("linen_sandals_t1.png"),
  "Linen Skirt": img("linen_skirt_t1.png"),
  "linen_skirt_t1": img("linen_skirt_t1.png"),
  "Linen Wraps": img("linen_wraps_t1.png"),
  "linen_wraps_t1": img("linen_wraps_t1.png"),
  "Silk Hat": img("silk_hat_t2.png"),
  "silk_hat_t2": img("silk_hat_t2.png"),
  "Silk Robe": img("silk_robe_t2.png"),
  "silk_robe_t2": img("silk_robe_t2.png"),
  "Silk Sandals": img("silk_sandals_t2.png"),
  "silk_sandals_t2": img("silk_sandals_t2.png"),
  "Silk Skirt": img("silk_skirt_t2.png"),
  "silk_skirt_t2": img("silk_skirt_t2.png"),
  "Silk Wraps": img("silk_wraps_t2.png"),
  "silk_wraps_t2": img("silk_wraps_t2.png"),
  "Mystic Hat": img("mystic_hat_t3.png"),
  "mystic_hat_t3": img("mystic_hat_t3.png"),
  "Mystic Robe": img("mystic_robe_t3.png"),
  "mystic_robe_t3": img("mystic_robe_t3.png"),
  "Mystic Sandals": img("mystic_sandals_t3.png"),
  "mystic_sandals_t3": img("mystic_sandals_t3.png"),
  "Mystic Skirt": img("mystic_skirt_t3.png"),
  "mystic_skirt_t3": img("mystic_skirt_t3.png"),
  "Mystic Wraps": img("mystic_wraps_t3.png"),
  "mystic_wraps_t3": img("mystic_wraps_t3.png"),
  "Oracle Hat": img("oracle_hat_t4.png"),
  "oracle_hat_t4": img("oracle_hat_t4.png"),
  "Oracle Robe": img("oracle_robe_t4.png"),
  "oracle_robe_t4": img("oracle_robe_t4.png"),
  "Oracle Sandals": img("oracle_sandals_t4.png"),
  "oracle_sandals_t4": img("oracle_sandals_t4.png"),
  "Oracle Skirt": img("oracle_skirt_t4.png"),
  "oracle_skirt_t4": img("oracle_skirt_t4.png"),
  "Oracle Wraps": img("oracle_wraps_t4.png"),
  "oracle_wraps_t4": img("oracle_wraps_t4.png"),
  "Arcane Hat": img("arcane_hat_t5.png"),
  "arcane_hat_t5": img("arcane_hat_t5.png"),
  "Arcane Robe": img("arcane_robe_t5.png"),
  "arcane_robe_t5": img("arcane_robe_t5.png"),
  "Arcane Sandals": img("arcane_sandals_t5.png"),
  "arcane_sandals_t5": img("arcane_sandals_t5.png"),
  "Arcane Skirt": img("arcane_skirt_t5.png"),
  "arcane_skirt_t5": img("arcane_skirt_t5.png"),
  "Arcane Wraps": img("arcane_wraps_t5.png"),
  "arcane_wraps_t5": img("arcane_wraps_t5.png"),
  "Divine Hat": img("divine_hat_t6.png"),
  "divine_hat_t6": img("divine_hat_t6.png"),
  "Divine Robe": img("divine_robe_t6.png"),
  "divine_robe_t6": img("divine_robe_t6.png"),
  "Divine Sandals": img("divine_sandals_t6.png"),
  "divine_sandals_t6": img("divine_sandals_t6.png"),
  "Divine Skirt": img("divine_skirt_t6.png"),
  "divine_skirt_t6": img("divine_skirt_t6.png"),
  "Divine Wraps": img("divine_wraps_t6.png"),
  "divine_wraps_t6": img("divine_wraps_t6.png"),
  "Celestial Hat": img("celestial_hat_t7.png"),
  "celestial_hat_t7": img("celestial_hat_t7.png"),
  "Celestial Robe": img("celestial_robe_t7.png"),
  "celestial_robe_t7": img("celestial_robe_t7.png"),
  "Celestial Sandals": img("celestial_sandals_t7.png"),
  "celestial_sandals_t7": img("celestial_sandals_t7.png"),
  "Celestial Skirt": img("celestial_skirt_t7.png"),
  "celestial_skirt_t7": img("celestial_skirt_t7.png"),
  "Celestial Wraps": img("celestial_wraps_t7.png"),
  "celestial_wraps_t7": img("celestial_wraps_t7.png"),
  "Void Cloth Hat": img("void_cloth_hat_t8.png"),
  "void_cloth_hat_t8": img("void_cloth_hat_t8.png"),
  "Void Cloth Robe": img("void_cloth_robe_t8.png"),
  "void_cloth_robe_t8": img("void_cloth_robe_t8.png"),
  "Void Cloth Sandals": img("void_cloth_sandals_t8.png"),
  "void_cloth_sandals_t8": img("void_cloth_sandals_t8.png"),
  "Void Cloth Skirt": img("void_cloth_skirt_t8.png"),
  "void_cloth_skirt_t8": img("void_cloth_skirt_t8.png"),
  "Void Cloth Wraps": img("void_cloth_wraps_t8.png"),
  "void_cloth_wraps_t8": img("void_cloth_wraps_t8.png"),

  // Potions
  "Minor Healing Potion": img("minor_healing_potion_icon.webp"),
  "Goblin Brew": img("goblin_brew_potion_icon.webp"),
  "Focus Elixir": img("focus_elixir_potion_icon.webp"),
  "Desert Shield Elixir": img("desert_shield_elixir_icon.webp"),
  "Antidote Potion": img("antidote_potion_icon.webp"),
  "Spider Venom Elixir": img("spider_venom_elixir_icon.webp"),
  "Wolf Fury Potion": img("wolf_fury_potion_icon.webp"),
  "Djinn Essence Potion": img("djinn_essence_potion_icon.webp"),
  "Dragon Heart Elixir": img("dragon_heart_elixir_icon.webp"),
  "Orc War Potion": img("orc_war_potion_icon.webp"),
  "Wyvern Scale Potion": img("wyvern_scale_potion_icon.webp"),
  "Phoenix Elixir": img("phoenix_elixir_potion_icon.webp"),
  "Infernal Potion": img("infernal_potion_icon.webp"),
  "XP Boost Potion": img("xp_boost_potion_icon.webp"),
  "Soft Fur Tonic": img("soft_fur_tonic_potion_icon.webp"),
  "Wolf Fang Elixir": img("wolf_fang_elixir_potion_icon.webp"),
  "Sand Storm Elixir": img("sand_storm_elixir_potion_icon.webp"),
  "Dark Essence Elixir": img("dark_essence_elixir_potion_icon.webp"),
  "Dragon Fire Elixir": img("dragon_fire_elixir_potion_icon.webp"),
  "Bat Wing Brew": img("bat_wing_brew_potion_icon.png"),
  "Mummy's Curse Antidote": img("mummy_curse_antidote_potion.png"),
  "Void Strength Potion": img("potion_void_strength.webp"),
  "Void Defence Potion": img("potion_void_defence.webp"),
  "Cosmic Elixir": img("potion_cosmic_elixir.webp"),
  "Frost Resistance Potion": img("potion_frost_resistance.webp"),
  "Dragon Fire Potion": img("potion_dragon_fire.webp"),
  "Minor HP Potion": img("potion_minor_hp.webp"),
  "Small HP Potion": img("potion_small_hp.webp"),
  "Frostbite Serum": img("potion_frostbite_serum.webp"),
  "Moonlight Elixir": img("potion_moonlight_elixir.webp"),
  "Obsidian Potion": img("potion_obsidian.webp"),
  "Shadow Draught": img("potion_shadow_draught.webp"),
  "Sun Crystal Tonic": img("potion_sun_crystal_tonic.webp"),
  "Void Essence Potion": img("potion_void_essence.webp"),

  // Enhancement / upgrade materials
  "chaos_stone": img("chaos_stone_icon.png"),
  "jurax_gem": img("jurax_gem_icon.png"),
  "death_liquid": img("death_liquid_icon.png"),
  "dungeon_dust": img("dungeon_dust_icon.png"),
  "dungeon_dust_tonic": img("dungeon_dust_icon.png"),
  "dungeon_ration": img("dungeon_ration_icon.png"),
  "cursed_bone": img("cursed_bone_icon.png"),
  "cursed_bone_elixir": img("cursed_bone_icon.png"),
  "cursed_bone_broth": img("cursed_bone_broth_icon.png"),
  "shadow_shard": img("shadow_shard_icon.png"),
  "shadow_stew": img("shadow_stew_icon.png"),
  "dragon_bone_soup": img("dragon_bone_soup_icon.png"),
  "void_feast": img("void_feast_icon.png"),
  "soul_gem": img("soul_gem_icon.png"),
  "soul_gem_tonic": img("soul_gem_icon.png"),
  "undead_essence": img("undead_essence_icon.png"),
  "void_essence_crystal": img("void_essence_crystal_icon.png"),
  "void_essence_draught": img("void_essence_crystal_icon.png"),
  "goblin_treasure_sack": img("goblin_treasure_sack_icon.png"),
  "goblin_crown": img("goblin_crown_icon.png"),
  "lich_staff": img("lich_staff_icon.png"),
  "dragon_fang_blade": img("dragon_fang_blade_icon.png"),
  "void_soulreaver": img("void_soulreaver_icon.png"),
  "dragon_bone": img("dragon_bone_icon.png"),
  "dragon_scale": img("dragon_scale_icon.png"),
  "teleport_stone": img("teleport_stone_icon.png"),
  "Spider Queen Fang": img("spider_queen_fang_icon.webp"),

  // Dungeon keys
  "bronze_key": img("bronze_key_icon.png"),
  "silver_key": img("silver_key_icon.png"),
  "gold_key": img("gold_key_icon.png"),
  "void_key": img("void_key_icon.png"),

  // Elemental essences
  "infernal_essence": img("infernal_essence_vial.png"),
  "Infernal Essence": img("infernal_essence_vial.png"),
  "frost_essence": img("frost_essence_vial.png"),
  "Frost Essence": img("frost_essence_vial.png"),
  "shadow_essence": img("shadow_essence_vial.png"),
  "Shadow Essence": img("shadow_essence_vial.png"),
  "thunder_essence": img("thunder_essence_vial.png"),
  "Thunder Essence": img("thunder_essence_vial.png"),

  // Boss chests
  "infernal_boss_chest": img("infernal_boss_chest_icon.png"),
  "Infernal Boss Chest": img("infernal_boss_chest_icon.png"),
  "frost_boss_chest": img("frost_boss_chest_icon.png"),
  "Frost Boss Chest": img("frost_boss_chest_icon.png"),
  "shadow_boss_chest": img("shadow_boss_chest_icon.png"),
  "Shadow Boss Chest": img("shadow_boss_chest_icon.png"),
  "thunder_boss_chest": img("thunder_boss_chest_icon.png"),
  "Thunder Boss Chest": img("thunder_boss_chest_icon.png"),
  "forge_core": img("forge_core_crystal.png"),
  "Forge Core": img("forge_core_crystal.png"),

  // Raid gear
  "raidbreaker_enhancement_stone": img("raidbreaker_enhancement_stone_icon.png"),
  "Raidbreaker Enhancement Stone": img("raidbreaker_enhancement_stone_icon.png"),
  "raid_plate_helm": img("equip_raid_plate_helm.png"),
  "Raid Plate Helm": img("equip_raid_plate_helm.png"),
  "raid_leather_hood": img("equip_raid_leather_hood.png"),
  "Raid Leather Hood": img("equip_raid_leather_hood.png"),
  "raid_cloth_hat": img("equip_raid_cloth_hat.png"),
  "Raid Cloth Hat": img("equip_raid_cloth_hat.png"),
  "raid_plate_body": img("equip_raid_plate_body.png"),
  "Raid Plate Body": img("equip_raid_plate_body.png"),
  "raid_leather_vest": img("equip_raid_leather_vest.png"),
  "Raid Leather Vest": img("equip_raid_leather_vest.png"),
  "raid_cloth_robe": img("equip_raid_cloth_robe.png"),
  "Raid Cloth Robe": img("equip_raid_cloth_robe.png"),
  "raid_plate_legs": img("equip_raid_plate_legs.png"),
  "Raid Plate Legs": img("equip_raid_plate_legs.png"),
  "raid_leather_pants": img("equip_raid_leather_pants.png"),
  "Raid Leather Pants": img("equip_raid_leather_pants.png"),
  "raid_cloth_skirt": img("equip_raid_cloth_skirt.png"),
  "Raid Cloth Skirt": img("equip_raid_cloth_skirt.png"),
  "raid_plate_boots": img("equip_raid_plate_boots.png"),
  "Raid Plate Boots": img("equip_raid_plate_boots.png"),
  "raid_leather_boots": img("equip_raid_leather_boots.png"),
  "Raid Leather Boots": img("equip_raid_leather_boots.png"),
  "raid_cloth_sandals": img("equip_raid_cloth_sandals.png"),
  "Raid Cloth Sandals": img("equip_raid_cloth_sandals.png"),
  "boss_chest_key": img("boss_chest_key_icon.png"),
  "Boss Chest Key": img("boss_chest_key_icon.png"),
  "weekly_power_token": img("weekly_power_token_icon.png"),
  "Weekly Power Token": img("weekly_power_token_icon.png"),
  "raid_conqueror_badge": img("raid_conqueror_badge.png"),
  "Raid Conqueror Badge": img("raid_conqueror_badge.png"),
};

// Simple placeholder SVG for missing images (dark fantasy themed)
const PLACEHOLDER_IMAGE = "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 64 64' fill='none'%3E%3Crect width='64' height='64' rx='8' fill='%231a1a2e'/%3E%3Cpath d='M32 20v12M32 38v2' stroke='%23666' stroke-width='3' stroke-linecap='round'/%3E%3Ccircle cx='32' cy='44' r='2' fill='%23666'/%3E%3C/svg%3E";

// Distinct "broken item" SVG used when an item ID cannot be resolved at all
// Red border + X marks it clearly as corrupted/unresolvable data
export const BROKEN_ITEM_IMAGE = "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 64 64' fill='none'%3E%3Crect width='64' height='64' rx='8' fill='%231e0a0a'/%3E%3Crect x='2' y='2' width='60' height='60' rx='7' stroke='%23dc2626' stroke-width='2' stroke-dasharray='4 2'/%3E%3Cline x1='20' y1='20' x2='44' y2='44' stroke='%23dc2626' stroke-width='3' stroke-linecap='round'/%3E%3Cline x1='44' y1='20' x2='20' y2='44' stroke='%23dc2626' stroke-width='3' stroke-linecap='round'/%3E%3C/svg%3E";


export function getItemImage(itemId: string): string {
  const { baseId } = parseItemWithRarity(itemId);
  
  const underscoreId = baseId.toLowerCase().replace(/\s+/g, '_');
  const spacedId = baseId.replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase());
  const item = getItemById(baseId) || getItemById(underscoreId) || getItemById(spacedId);
  
  const staticMatch = ITEM_IMAGES[baseId] || ITEM_IMAGES[itemId] || ITEM_IMAGES[underscoreId] || ITEM_IMAGES[spacedId] || ITEM_IMAGES[item?.id || ''];
  if (staticMatch) return staticMatch;
  
  if (item?.icon && (item.icon.includes('/') || item.icon.includes('.'))) {
    if (item.icon.startsWith('attached_assets/')) {
      return `/${item.icon}`;
    }
    return item.icon;
  }
  
  // Item is known but has no image yet — use generic placeholder
  if (item) return PLACEHOLDER_IMAGE;

  // Item ID is completely unrecognized — return broken item icon
  return BROKEN_ITEM_IMAGE;
}

// Export placeholder for use in onError handlers
export const ITEM_PLACEHOLDER = PLACEHOLDER_IMAGE;
