import type { Monster } from "@shared/schema";

export const MONSTERS: Monster[] = [
  // ===== VERDANT OUTSKIRTS (Yeşil Vadi) - Lvl 1-18 =====
  // Tier 1: Training - no gear needed
  {
    id: "chicken",
    name: "Chicken",
    region: "verdant",
    maxHitpoints: 8,
    attackLevel: 1,
    strengthLevel: 1,
    defenceLevel: 1,
    attackBonus: 0,
    strengthBonus: 0,
    attackSpeed: 3000,
    loot: [
      { itemId: "Raw Chicken", chance: 16.67, minQty: 1, maxQty: 1 },
      { itemId: "Feather", chance: 5, minQty: 1, maxQty: 2 },
    ],
    xpReward: { attack: 4, strength: 4, defence: 4, hitpoints: 1 },
  },
  {
    id: "rabbit",
    name: "Wild Rabbit",
    region: "verdant",
    maxHitpoints: 6,
    attackLevel: 1,
    strengthLevel: 1,
    defenceLevel: 2,
    attackBonus: 0,
    strengthBonus: 0,
    attackSpeed: 2800,
    loot: [
      { itemId: "Raw Rabbit", chance: 16.67, minQty: 1, maxQty: 1 },
      { itemId: "Soft Fur", chance: 7.5, minQty: 1, maxQty: 1 },
    ],
    xpReward: { attack: 3, strength: 3, defence: 3, hitpoints: 1 },
  },
  {
    id: "deer",
    name: "Deer",
    region: "verdant",
    maxHitpoints: 8,
    attackLevel: 5,
    strengthLevel: 3,
    defenceLevel: 3,
    attackBonus: 0,
    strengthBonus: 0,
    attackSpeed: 2600,
    loot: [
      { itemId: "Raw Meat", chance: 4, minQty: 1, maxQty: 1 },
      { itemId: "deer_hide", chance: 7.5, minQty: 1, maxQty: 1 },
      { itemId: "Bones", chance: 25, minQty: 1, maxQty: 1 },
    ],
    xpReward: { attack: 5, strength: 5, defence: 5, hitpoints: 1 },
  },
  {
    id: "wild_boar",
    name: "Wild Boar",
    region: "verdant",
    maxHitpoints: 12,
    attackLevel: 9,
    strengthLevel: 5,
    defenceLevel: 5,
    attackBonus: 0,
    strengthBonus: 0,
    attackSpeed: 2800,
    loot: [
      { itemId: "Raw Meat", chance: 4, minQty: 1, maxQty: 1 },
      { itemId: "boar_hide", chance: 7.5, minQty: 1, maxQty: 1 },
      { itemId: "normal_logs", chance: 2, minQty: 1, maxQty: 1 },
      { itemId: "Bones", chance: 20, minQty: 1, maxQty: 1 },
    ],
    xpReward: { attack: 6, strength: 6, defence: 6, hitpoints: 2 },
  },
  {
    id: "young_treant",
    name: "Young Treant",
    region: "verdant",
    maxHitpoints: 14,
    attackLevel: 12,
    strengthLevel: 5,
    defenceLevel: 10,
    attackBonus: 0,
    strengthBonus: 0,
    attackSpeed: 3200,
    loot: [
      { itemId: "normal_logs", chance: 2, minQty: 1, maxQty: 1 },
      { itemId: "oak_logs", chance: 2, minQty: 1, maxQty: 1 },
      { itemId: "Bones", chance: 15, minQty: 1, maxQty: 1 },
      { itemId: "Gold Coins", chance: 40, minQty: 3, maxQty: 10 },
      { itemId: "verdant_platelegs", chance: 0.2, minQty: 1, maxQty: 1 },
    ],
    xpReward: { attack: 7, strength: 7, defence: 7, hitpoints: 2 },
  },
  // Tier 2: Bronze gear recommended
  {
    id: "goblin",
    name: "Goblin",
    region: "verdant",
    maxHitpoints: 15,
    attackLevel: 14,
    strengthLevel: 6,
    defenceLevel: 8,
    attackBonus: 5,
    strengthBonus: 1,
    attackSpeed: 2800,
    loot: [
      { itemId: "Goblin Ear", chance: 25, minQty: 1, maxQty: 1 },
      { itemId: "Bronze Dagger", chance: 1.6, minQty: 1, maxQty: 1 },
      { itemId: "Gold Coins", chance: 60, minQty: 2, maxQty: 15 },
    ],
    xpReward: { attack: 8, strength: 8, defence: 8, hitpoints: 2 },
  },
  {
    id: "forest_spider",
    name: "Forest Spider",
    region: "verdant",
    maxHitpoints: 20,
    attackLevel: 18,
    strengthLevel: 10,
    defenceLevel: 12,
    attackBonus: 8,
    strengthBonus: 2,
    attackSpeed: 2600,
    loot: [
      { itemId: "Spider Silk", chance: 23.33, minQty: 1, maxQty: 2 },
      { itemId: "Gold Coins", chance: 50, minQty: 5, maxQty: 22 },
      { itemId: "oak_logs", chance: 2, minQty: 1, maxQty: 1 },
    ],
    xpReward: { attack: 10, strength: 10, defence: 10, hitpoints: 3 },
  },
  {
    id: "mountain_goat",
    name: "Mountain Goat",
    region: "verdant",
    maxHitpoints: 25,
    attackLevel: 21,
    strengthLevel: 14,
    defenceLevel: 15,
    attackBonus: 0,
    strengthBonus: 0,
    attackSpeed: 2600,
    loot: [
      { itemId: "Raw Meat", chance: 4, minQty: 1, maxQty: 1 },
      { itemId: "goat_pelt", chance: 7.5, minQty: 1, maxQty: 1 },
      { itemId: "Bones", chance: 27.5, minQty: 1, maxQty: 1 },
      { itemId: "Gold Coins", chance: 50, minQty: 5, maxQty: 20 },
      { itemId: "verdant_helm", chance: 0.2, minQty: 1, maxQty: 1 },
    ],
    xpReward: { attack: 12, strength: 12, defence: 12, hitpoints: 3 },
  },
  // Tier 3: Iron gear required
  {
    id: "wolf",
    name: "Wolf",
    region: "verdant",
    maxHitpoints: 30,
    attackLevel: 24,
    strengthLevel: 18,
    defenceLevel: 18,
    attackBonus: 6,
    strengthBonus: 3,
    attackSpeed: 2400,
    loot: [
      { itemId: "Wolf Pelt", chance: 7.5, minQty: 1, maxQty: 1 },
      { itemId: "Wolf Fang", chance: 11.67, minQty: 1, maxQty: 2 },
      { itemId: "Raw Meat", chance: 4, minQty: 1, maxQty: 1 },
      { itemId: "Gold Coins", chance: 55, minQty: 8, maxQty: 30 },
      { itemId: "verdant_boots", chance: 0.2, minQty: 1, maxQty: 1 },
    ],
    xpReward: { attack: 14, strength: 14, defence: 14, hitpoints: 4 },
  },
  {
    id: "bandit",
    name: "Bandit",
    region: "verdant",
    maxHitpoints: 40,
    attackLevel: 28,
    strengthLevel: 22,
    defenceLevel: 24,
    attackBonus: 9,
    strengthBonus: 4,
    attackSpeed: 2600,
    loot: [
      { itemId: "Iron Sword", chance: 1, minQty: 1, maxQty: 1 },
      { itemId: "Iron Dagger", chance: 1.6, minQty: 1, maxQty: 1 },
      { itemId: "Gold Coins", chance: 85, minQty: 15, maxQty: 60 },
      { itemId: "Bandit Mask", chance: 1, minQty: 1, maxQty: 1 },
      { itemId: "verdant_sword", chance: 0.15, minQty: 1, maxQty: 1 },
    ],
    xpReward: { attack: 18, strength: 18, defence: 18, hitpoints: 5 },
  },

  // ===== ASHEN QUARRY (Küllü Ocak) - Lvl 10-28 =====
  // Tier 4: Steel gear required
  {
    id: "rock_beetle",
    name: "Rock Beetle",
    region: "quarry",
    maxHitpoints: 60,
    attackLevel: 30,
    strengthLevel: 22,
    defenceLevel: 25,
    attackBonus: 0,
    strengthBonus: 0,
    attackSpeed: 2800,
    loot: [
      { itemId: "Copper Ore", chance: 2.5, minQty: 1, maxQty: 1 },
      { itemId: "Tin Ore", chance: 2, minQty: 1, maxQty: 1 },
      { itemId: "Coal", chance: 1.5, minQty: 1, maxQty: 1 },
      { itemId: "Gold Coins", chance: 45, minQty: 8, maxQty: 25 },
      { itemId: "Steel Buckler", chance: 0.25, minQty: 1, maxQty: 1 },
    ],
    xpReward: { attack: 22, strength: 22, defence: 22, hitpoints: 7 },
  },
  {
    id: "cave_bat",
    name: "Cave Bat",
    region: "quarry",
    maxHitpoints: 55,
    attackLevel: 28,
    strengthLevel: 18,
    defenceLevel: 20,
    attackBonus: 18,
    strengthBonus: 4,
    attackSpeed: 2200,
    loot: [
      { itemId: "Bat Wing", chance: 8, minQty: 1, maxQty: 2 },
      { itemId: "Gold Coins", chance: 40, minQty: 8, maxQty: 22 },
    ],
    xpReward: { attack: 20, strength: 20, defence: 20, hitpoints: 6 },
  },
  {
    id: "skeleton",
    name: "Skeleton",
    region: "quarry",
    maxHitpoints: 70,
    attackLevel: 32,
    strengthLevel: 28,
    defenceLevel: 28,
    attackBonus: 15,
    strengthBonus: 5,
    attackSpeed: 2600,
    loot: [
      { itemId: "Bones", chance: 50, minQty: 1, maxQty: 1 },
      { itemId: "Iron Sword", chance: 2.4, minQty: 1, maxQty: 1 },
      { itemId: "Coal", chance: 1.5, minQty: 1, maxQty: 1 },
      { itemId: "Gold Coins", chance: 60, minQty: 8, maxQty: 38 },
    ],
    xpReward: { attack: 26, strength: 26, defence: 26, hitpoints: 8 },
  },
  {
    id: "cave_serpent",
    name: "Cave Serpent",
    region: "quarry",
    maxHitpoints: 80,
    attackLevel: 35,
    strengthLevel: 32,
    defenceLevel: 30,
    attackBonus: 0,
    strengthBonus: 0,
    attackSpeed: 2400,
    loot: [
      { itemId: "Iron Ore", chance: 1.5, minQty: 1, maxQty: 1 },
      { itemId: "Coal", chance: 2, minQty: 1, maxQty: 1 },
      { itemId: "Raw Meat", chance: 4, minQty: 1, maxQty: 1 },
      { itemId: "Bones", chance: 27.5, minQty: 1, maxQty: 1 },
      { itemId: "Gold Coins", chance: 60, minQty: 12, maxQty: 35 },
    ],
    xpReward: { attack: 30, strength: 30, defence: 30, hitpoints: 9 },
    skills: [{
      id: "venom_bite",
      name: "Venomous Bite",
        nameTranslations: { tr: "Zehirli Isırık" },
      chance: 18,
      type: "poison",
      dotDamage: 2,
      dotDuration: 5,
    }],
  },
  // Tier 5: Mithril gear required
  {
    id: "rock_golem",
    name: "Rock Golem",
    region: "quarry",
    maxHitpoints: 100,
    attackLevel: 36,
    strengthLevel: 35,
    defenceLevel: 38,
    attackBonus: 15,
    strengthBonus: 6,
    attackSpeed: 3200,
    loot: [
      { itemId: "Iron Ore", chance: 2, minQty: 1, maxQty: 2 },
      { itemId: "Coal", chance: 1.5, minQty: 1, maxQty: 2 },
      { itemId: "Silver Ore", chance: 1.5, minQty: 1, maxQty: 1 },
      { itemId: "Golem Core", chance: 0.5, minQty: 1, maxQty: 1 },
      { itemId: "Gold Coins", chance: 70, minQty: 22, maxQty: 75 },
      { itemId: "quarry_helm", chance: 0.2, minQty: 1, maxQty: 1 },
    ],
    xpReward: { attack: 35, strength: 35, defence: 35, hitpoints: 10 },
    skills: [{
      id: "earthquake",
      name: "Earthquake",
        nameTranslations: { tr: "Deprem" },
      chance: 20,
      type: "stun",
      stunDuration: 2,
    }],
  },
  {
    id: "cave_troll",
    name: "Cave Troll",
    region: "quarry",
    maxHitpoints: 120,
    attackLevel: 40,
    strengthLevel: 45,
    defenceLevel: 42,
    attackBonus: 12,
    strengthBonus: 10,
    attackSpeed: 3400,
    loot: [
      { itemId: "Troll Hammer Piece", chance: 0.8, minQty: 1, maxQty: 1 },
      { itemId: "Iron Bar", chance: 2, minQty: 1, maxQty: 1 },
      { itemId: "Raw Meat", chance: 4, minQty: 1, maxQty: 2 },
      { itemId: "willow_logs", chance: 1.5, minQty: 1, maxQty: 1 },
      { itemId: "Gold Coins", chance: 75, minQty: 30, maxQty: 100 },
      { itemId: "quarry_boots", chance: 0.2, minQty: 1, maxQty: 1 },
    ],
    xpReward: { attack: 40, strength: 40, defence: 40, hitpoints: 12 },
    skills: [{
      id: "troll_smash",
      name: "Troll Smash",
        nameTranslations: { tr: "Trol Darbesi" },
      chance: 18,
      type: "stun",
      stunDuration: 1,
    }],
  },
  {
    id: "zombie",
    name: "Zombie",
    region: "quarry",
    maxHitpoints: 85,
    attackLevel: 38,
    strengthLevel: 38,
    defenceLevel: 35,
    attackBonus: 17,
    strengthBonus: 6,
    attackSpeed: 3000,
    loot: [
      { itemId: "Rotten Flesh", chance: 33.33, minQty: 1, maxQty: 2 },
      { itemId: "Bones", chance: 40, minQty: 1, maxQty: 1 },
      { itemId: "Steel Helmet", chance: 1.2, minQty: 1, maxQty: 1 },
      { itemId: "Gold Coins", chance: 65, minQty: 22, maxQty: 110 },
      { itemId: "quarry_platelegs", chance: 0.2, minQty: 1, maxQty: 1 },
    ],
    xpReward: { attack: 32, strength: 32, defence: 32, hitpoints: 9 },
  },
  // Tier 6: Mithril+ gear required
  {
    id: "mine_foreman",
    name: "Mine Foreman",
    region: "quarry",
    maxHitpoints: 140,
    attackLevel: 42,
    strengthLevel: 45,
    defenceLevel: 45,
    attackBonus: 17,
    strengthBonus: 8,
    attackSpeed: 2800,
    loot: [
      { itemId: "Steel Bar", chance: 1.5, minQty: 1, maxQty: 1 },
      { itemId: "Iron Bar", chance: 2, minQty: 1, maxQty: 1 },
      { itemId: "Mithril Ore", chance: 0.25, minQty: 1, maxQty: 1 },
      { itemId: "Gold Coins", chance: 85, minQty: 45, maxQty: 150 },
      { itemId: "Quarry Amulet", chance: 0.17, minQty: 1, maxQty: 1 },
      { itemId: "quarry_pickaxe", chance: 0.15, minQty: 1, maxQty: 1 },
    ],
    xpReward: { attack: 45, strength: 45, defence: 45, hitpoints: 14 },
    skills: [{
      id: "pickaxe_strike",
      name: "Pickaxe Strike",
        nameTranslations: { tr: "Kazma Darbesi" },
      chance: 25,
      type: "critical",
    }],
  },

  // ===== STARLIT DUNES (Yıldız Çölü) - Lvl 18-36 =====
  // Tier 7: Adamant gear required
  {
    id: "desert_fox",
    name: "Desert Fox",
    region: "dunes",
    maxHitpoints: 65,
    attackLevel: 46,
    strengthLevel: 44,
    defenceLevel: 44,
    attackBonus: 0,
    strengthBonus: 0,
    attackSpeed: 2200,
    loot: [
      { itemId: "fox_pelt", chance: 7.5, minQty: 1, maxQty: 1 },
      { itemId: "Raw Meat", chance: 4, minQty: 1, maxQty: 1 },
      { itemId: "Bones", chance: 22.5, minQty: 1, maxQty: 1 },
      { itemId: "Gold Coins", chance: 60, minQty: 15, maxQty: 40 },
    ],
    xpReward: { attack: 24, strength: 24, defence: 24, hitpoints: 7 },
  },
  {
    id: "cactus_beast",
    name: "Cactus Beast",
    region: "dunes",
    maxHitpoints: 80,
    attackLevel: 50,
    strengthLevel: 48,
    defenceLevel: 52,
    attackBonus: 0,
    strengthBonus: 0,
    attackSpeed: 3000,
    loot: [
      { itemId: "cactus_logs", chance: 2.5, minQty: 1, maxQty: 1 },
      { itemId: "Gold Ore", chance: 2.5, minQty: 1, maxQty: 1 },
      { itemId: "Bones", chance: 20, minQty: 1, maxQty: 1 },
      { itemId: "Gold Coins", chance: 55, minQty: 20, maxQty: 55 },
    ],
    xpReward: { attack: 30, strength: 30, defence: 30, hitpoints: 8 },
    skills: [{
      id: "thorn_spray",
      name: "Thorn Rain",
        nameTranslations: { tr: "Diken Yağmuru" },
      chance: 20,
      type: "combo",
      hits: 2,
    }],
  },
  {
    id: "desert_scorpion",
    name: "Desert Scorpion",
    region: "dunes",
    maxHitpoints: 55,
    attackLevel: 42,
    strengthLevel: 40,
    defenceLevel: 42,
    attackBonus: 15,
    strengthBonus: 8,
    attackSpeed: 2400,
    loot: [
      { itemId: "Scorpion Stinger", chance: 18.33, minQty: 1, maxQty: 1 },
      { itemId: "Venom Sac", chance: 11.67, minQty: 1, maxQty: 1 },
      { itemId: "Gold Coins", chance: 60, minQty: 15, maxQty: 52 },
    ],
    xpReward: { attack: 20, strength: 20, defence: 20, hitpoints: 6 },
    skills: [{
      id: "venomous_sting",
      name: "Venomous Sting",
        nameTranslations: { tr: "Zehirli İğne" },
      chance: 30,
      type: "poison",
      dotDamage: 3,
      dotDuration: 8,
    }],
  },
  {
    id: "giant_spider",
    name: "Giant Spider",
    region: "dunes",
    maxHitpoints: 70,
    attackLevel: 48,
    strengthLevel: 48,
    defenceLevel: 50,
    attackBonus: 16,
    strengthBonus: 10,
    attackSpeed: 2400,
    loot: [
      { itemId: "Spider Silk", chance: 8, minQty: 1, maxQty: 2 },
      { itemId: "Venom Sac", chance: 13.33, minQty: 1, maxQty: 3 },
      { itemId: "Spider Queen Fang", chance: 1, minQty: 1, maxQty: 1 },
      { itemId: "willow_logs", chance: 1.5, minQty: 1, maxQty: 1 },
      { itemId: "Gold Coins", chance: 70, minQty: 22, maxQty: 90 },
      { itemId: "Spider Queen Staff", chance: 0.15, minQty: 1, maxQty: 1 },
    ],
    xpReward: { attack: 28, strength: 28, defence: 28, hitpoints: 8 },
  },
  {
    id: "sand_worm",
    name: "Sand Worm",
    region: "dunes",
    maxHitpoints: 120,
    attackLevel: 55,
    strengthLevel: 52,
    defenceLevel: 50,
    attackBonus: 0,
    strengthBonus: 0,
    attackSpeed: 2800,
    loot: [
      { itemId: "Sand Essence", chance: 16.67, minQty: 1, maxQty: 1 },
      { itemId: "Silver Ore", chance: 1.5, minQty: 1, maxQty: 1 },
      { itemId: "Bones", chance: 17.5, minQty: 1, maxQty: 1 },
      { itemId: "Gold Coins", chance: 65, minQty: 25, maxQty: 65 },
      { itemId: "dunes_boots", chance: 0.2, minQty: 1, maxQty: 1 },
    ],
    xpReward: { attack: 32, strength: 32, defence: 32, hitpoints: 9 },
    skills: [{
      id: "burrow_strike",
      name: "Underground Assault",
        nameTranslations: { tr: "Yeraltı Saldırısı" },
      chance: 15,
      type: "stun",
      stunDuration: 2,
    }],
  },
  // Tier 8: Adamant+ gear required
  {
    id: "sand_elemental",
    name: "Sand Elemental",
    region: "dunes",
    maxHitpoints: 90,
    attackLevel: 52,
    strengthLevel: 55,
    defenceLevel: 58,
    attackBonus: 16,
    strengthBonus: 12,
    attackSpeed: 2800,
    loot: [
      { itemId: "Sand Essence", chance: 8, minQty: 1, maxQty: 1 },
      { itemId: "Gold Ore", chance: 1.5, minQty: 1, maxQty: 1 },
      { itemId: "Gold Coins", chance: 75, minQty: 38, maxQty: 120 },
      { itemId: "dunes_helm", chance: 0.2, minQty: 1, maxQty: 1 },
    ],
    xpReward: { attack: 35, strength: 35, defence: 35, hitpoints: 10 },
  },
  {
    id: "mummy",
    name: "Mummy",
    region: "dunes",
    maxHitpoints: 110,
    attackLevel: 60,
    strengthLevel: 62,
    defenceLevel: 65,
    attackBonus: 12,
    strengthBonus: 14,
    attackSpeed: 3000,
    loot: [
      { itemId: "Ancient Bandage", chance: 8.34, minQty: 1, maxQty: 3 },
      { itemId: "Gold Bar", chance: 1.5, minQty: 1, maxQty: 1 },
      { itemId: "Bones", chance: 22.5, minQty: 1, maxQty: 2 },
      { itemId: "Gold Coins", chance: 80, minQty: 60, maxQty: 180 },
      { itemId: "Desert Cape", chance: 0.27, minQty: 1, maxQty: 1 },
      { itemId: "dunes_platelegs", chance: 0.2, minQty: 1, maxQty: 1 },
      { itemId: "Mummy Lord Staff", chance: 0.12, minQty: 1, maxQty: 1 },
    ],
    xpReward: { attack: 42, strength: 42, defence: 42, hitpoints: 12 },
    skills: [{
      id: "curse",
      name: "Curse",
        nameTranslations: { tr: "Lanet" },
      chance: 25,
      type: "burn",
      dotDamage: 0,
      dotDuration: 6,
      healingReduction: 0.5,
    }],
  },
  // Tier 9: Rune gear required
  {
    id: "djinn",
    name: "Djinn",
    region: "dunes",
    maxHitpoints: 140,
    attackLevel: 68,
    strengthLevel: 72,
    defenceLevel: 75,
    attackBonus: 11,
    strengthBonus: 16,
    attackSpeed: 2600,
    loot: [
      { itemId: "Djinn Essence", chance: 13.33, minQty: 1, maxQty: 1 },
      { itemId: "Mithril Bar", chance: 2, minQty: 1, maxQty: 1 },
      { itemId: "Gold Coins", chance: 90, minQty: 90, maxQty: 270 },
      { itemId: "Starlit Amulet", chance: 0.17, minQty: 1, maxQty: 1 },
      { itemId: "sun_blade", chance: 0.15, minQty: 1, maxQty: 1 },
    ],
    xpReward: { attack: 50, strength: 50, defence: 50, hitpoints: 15 },
    skills: [{
      id: "sandstorm",
      name: "Sandstorm",
        nameTranslations: { tr: "Kum Fırtınası" },
      chance: 30,
      type: "stun",
      stunDuration: 2,
    }, {
      id: "magic_shield",
      name: "Magic Shield",
      nameTranslations: { tr: "Büyü Kalkanı" },
      chance: 100,
      type: "magic_shield",
      magicShieldPercent: 30,
    }],
  },

  // ===== OBSIDIAN KEEP (Obsidyen Kale) - Lvl 30-50 =====
  // Tier 10: Rune gear required
  {
    id: "dark_panther",
    name: "Dark Panther",
    region: "obsidian",
    maxHitpoints: 110,
    attackLevel: 65,
    strengthLevel: 65,
    defenceLevel: 62,
    attackBonus: 0,
    strengthBonus: 0,
    attackSpeed: 2200,
    loot: [
      { itemId: "panther_pelt", chance: 7.5, minQty: 1, maxQty: 1 },
      { itemId: "Dark Essence", chance: 5, minQty: 1, maxQty: 1 },
      { itemId: "Raw Meat", chance: 4, minQty: 1, maxQty: 1 },
      { itemId: "Bones", chance: 25, minQty: 1, maxQty: 1 },
      { itemId: "Gold Coins", chance: 65, minQty: 30, maxQty: 80 },
    ],
    xpReward: { attack: 38, strength: 38, defence: 38, hitpoints: 11 },
    skills: [{
      id: "shadow_pounce",
      name: "Shadow Strike",
        nameTranslations: { tr: "Gölge Saldırısı" },
      chance: 22,
      type: "critical",
    }],
  },
  {
    id: "orc_grunt",
    name: "Orc Grunt",
    region: "obsidian",
    maxHitpoints: 100,
    attackLevel: 62,
    strengthLevel: 62,
    defenceLevel: 60,
    attackBonus: 19,
    strengthBonus: 16,
    attackSpeed: 2600,
    loot: [
      { itemId: "Orc Tusk", chance: 16.67, minQty: 1, maxQty: 1 },
      { itemId: "Steel Sword", chance: 1.6, minQty: 1, maxQty: 1 },
      { itemId: "Raw Meat", chance: 4, minQty: 1, maxQty: 1 },
      { itemId: "Gold Coins", chance: 70, minQty: 38, maxQty: 120 },
    ],
    xpReward: { attack: 35, strength: 35, defence: 35, hitpoints: 10 },
  },
  {
    id: "orc_warrior",
    name: "Orc Warrior",
    region: "obsidian",
    maxHitpoints: 130,
    attackLevel: 70,
    strengthLevel: 75,
    defenceLevel: 70,
    attackBonus: 16,
    strengthBonus: 20,
    attackSpeed: 2600,
    loot: [
      { itemId: "Orc Tusk", chance: 23.33, minQty: 1, maxQty: 3 },
      { itemId: "Mithril Sword", chance: 1, minQty: 1, maxQty: 1 },
      { itemId: "Orc Axe Piece", chance: 1.67, minQty: 1, maxQty: 1 },
      { itemId: "Gold Coins", chance: 80, minQty: 90, maxQty: 270 },
      { itemId: "obsidian_platelegs", chance: 0.2, minQty: 1, maxQty: 1 },
      { itemId: "Orc Shaman Staff", chance: 0.12, minQty: 1, maxQty: 1 },
    ],
    xpReward: { attack: 48, strength: 48, defence: 48, hitpoints: 14 },
  },
  {
    id: "shadow_wolf",
    name: "Shadow Wolf",
    region: "obsidian",
    maxHitpoints: 140,
    attackLevel: 72,
    strengthLevel: 72,
    defenceLevel: 68,
    attackBonus: 0,
    strengthBonus: 0,
    attackSpeed: 2400,
    loot: [
      { itemId: "shadow_wolf_pelt", chance: 7.5, minQty: 1, maxQty: 1 },
      { itemId: "Obsidian Shard", chance: 4, minQty: 1, maxQty: 1 },
      { itemId: "Raw Meat", chance: 4, minQty: 1, maxQty: 1 },
      { itemId: "Bones", chance: 25, minQty: 1, maxQty: 1 },
      { itemId: "Gold Coins", chance: 70, minQty: 40, maxQty: 100 },
    ],
    xpReward: { attack: 46, strength: 46, defence: 46, hitpoints: 13 },
    skills: [{
      id: "howl",
      name: "Howling Wail",
        nameTranslations: { tr: "Uğultulu Uluma" },
      chance: 18,
      type: "armor_break",
      armorBreakPercent: 20,
      armorBreakDuration: 4,
    }],
  },
  {
    id: "hill_giant",
    name: "Hill Giant",
    region: "obsidian",
    maxHitpoints: 200,
    attackLevel: 75,
    strengthLevel: 90,
    defenceLevel: 72,
    attackBonus: 14,
    strengthBonus: 28,
    attackSpeed: 3600,
    loot: [
      { itemId: "Giant's Hammer Shard", chance: 0.83, minQty: 1, maxQty: 1 },
      { itemId: "Raw Meat", chance: 5, minQty: 1, maxQty: 2 },
      { itemId: "Bones", chance: 25, minQty: 1, maxQty: 2 },
      { itemId: "Rune Bar", chance: 0.5, minQty: 1, maxQty: 1 },
      { itemId: "maple_logs", chance: 2, minQty: 1, maxQty: 1 },
      { itemId: "Gold Coins", chance: 90, minQty: 150, maxQty: 400 },
      { itemId: "obsidian_helm", chance: 0.2, minQty: 1, maxQty: 1 },
    ],
    xpReward: { attack: 55, strength: 55, defence: 55, hitpoints: 16 },
    skills: [{
      id: "giant_stomp",
      name: "Giant Stomp",
        nameTranslations: { tr: "Dev Basışı" },
      chance: 22,
      type: "stun",
      stunDuration: 2,
    }],
  },
  // Tier 11: Dragon gear required
  {
    id: "shadow_stalker",
    name: "Shadow Stalker",
    region: "obsidian",
    maxHitpoints: 160,
    attackLevel: 78,
    strengthLevel: 85,
    defenceLevel: 80,
    attackBonus: 15,
    strengthBonus: 24,
    attackSpeed: 2200,
    loot: [
      { itemId: "Dark Essence", chance: 8, minQty: 1, maxQty: 1 },
      { itemId: "Shadow Cloak", chance: 0.67, minQty: 1, maxQty: 1 },
      { itemId: "Shadow Dagger Piece", chance: 1, minQty: 1, maxQty: 1 },
      { itemId: "Gold Coins", chance: 75, minQty: 75, maxQty: 225 },
      { itemId: "obsidian_boots", chance: 0.2, minQty: 1, maxQty: 1 },
      { itemId: "Shadow Dagger", chance: 0.15, minQty: 1, maxQty: 1 },
    ],
    xpReward: { attack: 58, strength: 58, defence: 58, hitpoints: 17 },
    skills: [{
      id: "shadow_blade",
      name: "Shadow Blade",
        nameTranslations: { tr: "Gölge Bıçağı" },
      chance: 30,
      type: "critical",
    }],
  },
  {
    id: "dark_knight",
    name: "Dark Knight",
    region: "obsidian",
    maxHitpoints: 200,
    attackLevel: 85,
    strengthLevel: 95,
    defenceLevel: 90,
    attackBonus: 14,
    strengthBonus: 28,
    attackSpeed: 2400,
    loot: [
      { itemId: "Dark Essence", chance: 8, minQty: 1, maxQty: 2 },
      { itemId: "Adamant Sword", chance: 0.8, minQty: 1, maxQty: 1 },
      { itemId: "Mithril Armor", chance: 0.6, minQty: 1, maxQty: 1 },
      { itemId: "Dark Knight Sword Piece", chance: 1.33, minQty: 1, maxQty: 1 },
      { itemId: "Gold Coins", chance: 90, minQty: 120, maxQty: 375 },
      { itemId: "Obsidian Cape", chance: 0.13, minQty: 1, maxQty: 1 },
    ],
    xpReward: { attack: 70, strength: 70, defence: 70, hitpoints: 22 },
    skills: [{
      id: "death_strike",
      name: "Death Strike",
        nameTranslations: { tr: "Ölüm Darbesi" },
      chance: 30,
      type: "combo",
      hits: 3,
    }],
  },
  // Tier 12: Dragon+ gear required
  {
    id: "dark_lord",
    name: "Dark Lord",
    region: "obsidian",
    maxHitpoints: 250,
    attackLevel: 95,
    strengthLevel: 105,
    defenceLevel: 100,
    attackBonus: 13,
    strengthBonus: 32,
    attackSpeed: 2600,
    loot: [
      { itemId: "Dark Essence", chance: 8, minQty: 1, maxQty: 2 },
      { itemId: "Rune Bar", chance: 1, minQty: 1, maxQty: 1 },
      { itemId: "Shadow Blade", chance: 0.67, minQty: 1, maxQty: 1 },
      { itemId: "Dark Lord Fragment", chance: 0.5, minQty: 1, maxQty: 1 },
      { itemId: "Gold Coins", chance: 100, minQty: 225, maxQty: 600 },
      { itemId: "Nightfall Amulet", chance: 0.1, minQty: 1, maxQty: 1 },
    ],
    xpReward: { attack: 85, strength: 85, defence: 85, hitpoints: 28 },
    skills: [{
      id: "dark_aura",
      name: "Dark Aura",
        nameTranslations: { tr: "Karanlık Aura" },
      chance: 25,
      type: "enrage",
      enrageThreshold: 30,
      enrageDamageBoost: 1.5,
    }, {
      id: "armor_repair",
      name: "Dark Armor Repair",
      nameTranslations: { tr: "Karanlık Zırh Onarımı" },
      chance: 100,
      type: "armor_repair",
      armorRepairPerTurn: 8,
      armorRepairCap: 80,
    }],
  },

  {
    id: "frost_tiger",
    name: "Frost Tiger",
    region: "frozen_wastes",
    maxHitpoints: 380,
    attackLevel: 73,
    strengthLevel: 88,
    defenceLevel: 86,
    attackBonus: 0,
    strengthBonus: 0,
    attackSpeed: 2400,
    loot: [
      { itemId: "frost_tiger_pelt", chance: 7.5, minQty: 1, maxQty: 1 },
      { itemId: "Frozen Essence", chance: 6, minQty: 1, maxQty: 1 },
      { itemId: "Raw Meat", chance: 4, minQty: 1, maxQty: 1 },
      { itemId: "Bones", chance: 25, minQty: 1, maxQty: 2 },
      { itemId: "Gold Coins", chance: 65, minQty: 60, maxQty: 140 },
    ],
    xpReward: { attack: 85, strength: 85, defence: 85, hitpoints: 26 },
    skills: [{
      id: "frost_claw",
      name: "Frost Claw",
        nameTranslations: { tr: "Buz Pençesi" },
      chance: 20,
      type: "critical",
    }, {
      id: "freezing_roar",
      name: "Freezing Roar",
        nameTranslations: { tr: "Dondurucu Kükreme" },
      chance: 12,
      type: "stun",
      stunDuration: 2,
    }],
  },

  // ===== DRAGONSPIRE SUMMIT (Ejder Zirvesi) - Lvl 38-70 =====
  // Tier 13: Dragon gear required, high combat stats
  {
    id: "young_wyvern",
    name: "Young Wyvern",
    region: "dragonspire",
    maxHitpoints: 280,
    attackLevel: 90,
    strengthLevel: 85,
    defenceLevel: 80,
    attackBonus: 0,
    strengthBonus: 0,
    attackSpeed: 2600,
    loot: [
      { itemId: "Wyvern Scale", chance: 8.34, minQty: 1, maxQty: 1 },
      { itemId: "dragon_bone", chance: 2.5, minQty: 1, maxQty: 1 },
      { itemId: "Raw Wyvern Meat", chance: 11.67, minQty: 1, maxQty: 2 },
      { itemId: "Bones", chance: 20, minQty: 1, maxQty: 2 },
      { itemId: "Gold Coins", chance: 70, minQty: 80, maxQty: 180 },
    ],
    xpReward: { attack: 55, strength: 55, defence: 55, hitpoints: 16 },
    skills: [{
      id: "wing_gust",
      name: "Wing Gust",
        nameTranslations: { tr: "Kanat Rüzgarı" },
      chance: 15,
      type: "stun",
      stunDuration: 1,
    }],
  },
  {
    id: "wyvern",
    name: "Wyvern",
    region: "dragonspire",
    maxHitpoints: 180,
    attackLevel: 90,
    strengthLevel: 82,
    defenceLevel: 78,
    attackBonus: 22,
    strengthBonus: 30,
    attackSpeed: 2400,
    loot: [
      { itemId: "Wyvern Scale", chance: 4, minQty: 1, maxQty: 2 },
      { itemId: "Raw Wyvern Meat", chance: 4, minQty: 1, maxQty: 2 },
      { itemId: "Wyvern Wing Fragment", chance: 1, minQty: 1, maxQty: 1 },
      { itemId: "Bones", chance: 17.5, minQty: 1, maxQty: 2 },
      { itemId: "Gold Coins", chance: 80, minQty: 90, maxQty: 270 },
    ],
    xpReward: { attack: 60, strength: 60, defence: 60, hitpoints: 18 },
  },
  // Tier 14: Best gear required
  {
    id: "fire_drake",
    name: "Fire Drake",
    region: "dragonspire",
    maxHitpoints: 240,
    attackLevel: 96,
    strengthLevel: 98,
    defenceLevel: 92,
    attackBonus: 23,
    strengthBonus: 36,
    attackSpeed: 2600,
    loot: [
      { itemId: "Drake Scale", chance: 4, minQty: 1, maxQty: 2 },
      { itemId: "Dragon Bone", chance: 4, minQty: 1, maxQty: 2 },
      { itemId: "Fire Essence", chance: 10, minQty: 1, maxQty: 2 },
      { itemId: "Drake Fire Essence", chance: 0.67, minQty: 1, maxQty: 1 },
      { itemId: "Gold Coins", chance: 85, minQty: 150, maxQty: 450 },
      { itemId: "Drake Staff", chance: 0.12, minQty: 1, maxQty: 1 },
    ],
    xpReward: { attack: 80, strength: 80, defence: 80, hitpoints: 25 },
    skills: [{
      id: "fire_breath",
      name: "Fire Breath",
        nameTranslations: { tr: "Ateş Nefesi" },
      chance: 30,
      type: "combo",
      hits: 4,
      dotDamage: 5,
      dotDuration: 6,
      healingReduction: 0.5,
    }, {
      id: "evasion_aura",
      name: "Evasion Aura",
      nameTranslations: { tr: "Kaçınma Aurası" },
      type: "evasion_aura",
      chance: 100,
      evasionBonus: 25,
    }],
  },
  // Tier 15: End-game content
  {
    id: "elder_dragon",
    name: "Elder Dragon",
    region: "dragonspire",
    maxHitpoints: 320,
    attackLevel: 105,
    strengthLevel: 115,
    defenceLevel: 105,
    attackBonus: 25,
    strengthBonus: 42,
    attackSpeed: 2800,
    loot: [
      { itemId: "Dragon Scale", chance: 4, minQty: 1, maxQty: 2 },
      { itemId: "Dragon Bone", chance: 5, minQty: 1, maxQty: 2 },
      { itemId: "Rune Sword", chance: 1, minQty: 1, maxQty: 1 },
      { itemId: "Elder Dragon Heart", chance: 0.5, minQty: 1, maxQty: 1 },
      { itemId: "Dragon Hammer Head", chance: 0.33, minQty: 1, maxQty: 1 },
      { itemId: "Gold Coins", chance: 100, minQty: 300, maxQty: 750 },
      { itemId: "Dragonfire Cape", chance: 0.1, minQty: 1, maxQty: 1 },
    ],
    xpReward: { attack: 100, strength: 100, defence: 100, hitpoints: 32 },
    skills: [{
      id: "flame_breath",
      name: "Flame Breath",
        nameTranslations: { tr: "Alev Nefesi" },
      chance: 35,
      type: "burn",
      dotDamage: 10,
      dotDuration: 6,
    }, {
      id: "regeneration",
      name: "Regeneration",
      nameTranslations: { tr: "Can Yenileme" },
      type: "regenerate_on_no_stun",
      chance: 100,
      selfHealPercent: 3,
    }],
  },
  // Tier 16: Boss tier - max stats required
  {
    id: "ancient_dragon",
    name: "Ancient Dragon",
    region: "dragonspire",
    maxHitpoints: 420,
    attackLevel: 115,
    strengthLevel: 130,
    defenceLevel: 120,
    attackBonus: 26,
    strengthBonus: 50,
    attackSpeed: 3000,
    loot: [
      { itemId: "Dragon Scale", chance: 5, minQty: 1, maxQty: 2 },
      { itemId: "Dragon Bone", chance: 5, minQty: 1, maxQty: 2 },
      { itemId: "Dragon Sword", chance: 0.5, minQty: 1, maxQty: 1 },
      { itemId: "Dragonbone Blade", chance: 0.27, minQty: 1, maxQty: 1 },
      { itemId: "Ancient Dragon Spirit", chance: 0.27, minQty: 1, maxQty: 1 },
      { itemId: "Gold Coins", chance: 100, minQty: 600, maxQty: 1500 },
      { itemId: "Dragon Amulet", chance: 0.07, minQty: 1, maxQty: 1 },
    ],
    xpReward: { attack: 120, strength: 120, defence: 120, hitpoints: 40 },
    skills: [{
      id: "ancient_flame",
      name: "Ancient Flame",
        nameTranslations: { tr: "Antik Alev" },
      chance: 25,
      type: "combo",
      hits: 5,
      dotDamage: 8,
      dotDuration: 8,
      healingReduction: 0.5,
      stunDuration: 2,
    }, {
      id: "evasion_aura",
      name: "Ancient Evasion",
      nameTranslations: { tr: "Antik Kaçınma" },
      chance: 100,
      type: "evasion_aura",
      evasionBonus: 20,
    }, {
      id: "regenerate_on_no_stun",
      name: "Dragon Regeneration",
      nameTranslations: { tr: "Ejderha Yenilenmesi" },
      chance: 100,
      type: "regenerate_on_no_stun",
      selfHealPercent: 2,
    }],
  },
  // Tier 17: Ultimate Boss - only for maxed players
  {
    id: "dragon_king",
    name: "Dragon King",
    region: "dragonspire",
    maxHitpoints: 550,
    attackLevel: 130,
    strengthLevel: 150,
    defenceLevel: 140,
    attackBonus: 21,
    strengthBonus: 60,
    attackSpeed: 2800,
    loot: [
      { itemId: "Dragon Scale", chance: 5, minQty: 1, maxQty: 2 },
      { itemId: "Dragon Bone", chance: 5, minQty: 1, maxQty: 2 },
      { itemId: "Dragon Platebody", chance: 0.17, minQty: 1, maxQty: 1 },
      { itemId: "Dragon Helmet", chance: 0.17, minQty: 1, maxQty: 1 },
      { itemId: "Gold Coins", chance: 100, minQty: 1200, maxQty: 3000 },
      { itemId: "Crown of Flames", chance: 0.03, minQty: 1, maxQty: 1 },
      { itemId: "Infernal Cape", chance: 0.05, minQty: 1, maxQty: 1 },
    ],
    xpReward: { attack: 150, strength: 150, defence: 150, hitpoints: 50 },
    skills: [{
      id: "king_breath",
      name: "King's Breath",
        nameTranslations: { tr: "Kral Nefesi" },
      chance: 25,
      type: "combo",
      hits: 6,
      dotDamage: 10,
      dotDuration: 10,
      healingReduction: 0.5,
      enrageThreshold: 25,
      enrageDamageBoost: 1.75,
    }, {
      id: "reflect_damage",
      name: "Damage Reflect",
      nameTranslations: { tr: "Hasar Yansıtma" },
      type: "reflect_damage",
      chance: 100,
      reflectPercent: 3,
      flatReflect: 30,
    }, {
      id: "magic_shield",
      name: "Infernal Shield",
      nameTranslations: { tr: "Cehennem Kalkanı" },
      chance: 100,
      type: "magic_shield",
      magicShieldPercent: 25,
    }],
  },
  {
    id: "void_beast",
    name: "Void Beast",
    region: "void_realm",
    maxHitpoints: 550,
    attackLevel: 88,
    strengthLevel: 100,
    defenceLevel: 98,
    attackBonus: 0,
    strengthBonus: 0,
    attackSpeed: 2600,
    loot: [
      { itemId: "void_beast_hide", chance: 7.5, minQty: 1, maxQty: 1 },
      { itemId: "Void Crystal", chance: 5, minQty: 1, maxQty: 1 },
      { itemId: "Bones", chance: 25, minQty: 1, maxQty: 2 },
      { itemId: "Gold Coins", chance: 65, minQty: 90, maxQty: 200 },
      { itemId: "void_boots", chance: 0.15, minQty: 1, maxQty: 1 },
    ],
    xpReward: { attack: 100, strength: 100, defence: 100, hitpoints: 38 },
    skills: [{
      id: "void_bite",
      name: "Void Bite",
        nameTranslations: { tr: "Boşluk Isırığı" },
      chance: 20,
      type: "critical",
    }, {
      id: "void_howl",
      name: "Void Howl",
        nameTranslations: { tr: "Boşluk Uluması" },
      chance: 15,
      type: "armor_break",
      armorBreakPercent: 25,
      armorBreakDuration: 5,
    }, {
      id: "reflect_damage",
      name: "Void Reflect",
      nameTranslations: { tr: "Boşluk Yansıması" },
      chance: 100,
      type: "reflect_damage",
      reflectPercent: 4,
      flatReflect: 35,
    }, {
      id: "armor_repair",
      name: "Void Armor",
      nameTranslations: { tr: "Boşluk Zırhı" },
      chance: 100,
      type: "armor_repair",
      armorRepairPerTurn: 10,
      armorRepairCap: 100,
    }],
  },
];
