const ASSET_BASE = "https://pub-87034a8f89f94b3d9149a9af7048ee14.r2.dev/";
const img = (f: string) => ASSET_BASE + "generated_images/" + f;

export const MONSTER_IMAGES: Record<string, string> = {
  chicken: img("monster_chicken_v2.png"),
  rabbit: img("monster_rabbit_v2.png"),
  goblin: img("monster_goblin_v2.png"),
  forest_spider: img("monster_forest_spider_v2.png"),
  wolf: img("monster_wolf_v2.png"),
  bandit: img("monster_bandit_v2.png"),
  cave_bat: img("monster_cave_bat_v2.png"),
  skeleton: img("monster_skeleton_v2.png"),
  rock_golem: img("monster_rock_golem_v2.png"),
  zombie: img("monster_zombie_v2.png"),
  mine_foreman: img("monster_mine_foreman_v4.png"),
  desert_scorpion: img("monster_desert_scorpion_v2.png"),
  giant_spider: img("monster_giant_spider_v2.png"),
  sand_elemental: img("monster_sand_elemental_v2.png"),
  mummy: img("monster_mummy_v2.png"),
  djinn: img("monster_djinn_v2.png"),
  orc_grunt: img("monster_orc_grunt_v2.png"),
  orc_warrior: img("monster_orc_warrior_v2.png"),
  shadow_stalker: img("monster_shadow_stalker_v2.png"),
  dark_knight: img("monster_dark_knight_v2.png"),
  dark_lord: img("monster_dark_lord_v2.png"),
  wyvern: img("monster_wyvern_v2.png"),
  fire_drake: img("monster_fire_drake_v2.png"),
  elder_dragon: img("monster_elder_dragon_v2.png"),
  ancient_dragon: img("monster_ancient_dragon_v2.png"),
  dragon_king: img("monster_dragon_king_v2.png"),
  ancient_ice_golem: img("monster_ancient_ice_golem_v3.png"),
  frost_dragon: img("monster_frost_dragon_v3.png"),
  frost_giant: img("monster_frost_giant_v3.png"),
  frost_witch: img("monster_frost_witch_v3.png"),
  ice_elemental: img("monster_ice_elemental_v3.png"),
  ice_wolf: img("monster_ice_wolf_v3.png"),
  shadow_demon: img("monster_shadow_demon_v3.png"),
  void_elemental: img("monster_void_elemental_v3.png"),
  void_king: img("monster_void_king_v3.png"),
  void_knight: img("monster_void_knight_v3.png"),
  void_lord: img("monster_void_lord_v3.png"),
  void_wraith: img("monster_void_wraith_v3.png"),
  cave_troll: img("monster_cave_troll_v2.png"),
  hill_giant: img("monster_hill_giant_v2.png"),
  goblin_king: img("monster_goblin_king_v2.png"),
  lich_lord: img("monster_lich_lord_v2.png"),
  deer: img("monster_deer_v2.png"),
  wild_boar: img("monster_wild_boar_v2.png"),
  young_treant: img("monster_young_treant_v2.png"),
  mountain_goat: img("monster_mountain_goat_v2.png"),
  rock_beetle: img("monster_rock_beetle_v2.png"),
  cave_serpent: img("monster_cave_serpent_v2.png"),
  desert_fox: img("monster_desert_fox_v2.png"),
  cactus_beast: img("monster_cactus_beast_v2.png"),
  sand_worm: img("monster_sand_worm_v2.png"),
  dark_panther: img("monster_dark_panther_v2.png"),
  shadow_wolf: img("monster_shadow_wolf_v2.png"),
  frost_tiger: img("monster_frost_tiger_v2.png"),
  young_wyvern: img("monster_young_wyvern_v2.png"),
  void_beast: img("monster_void_beast_v2.png"),
};

export function getMonsterImage(monsterId: string): string | undefined {
  return MONSTER_IMAGES[monsterId];
}
